apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{include "kong-base.name" .}}kong-ingress-clusterrole-nisa-binding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kong-base.name" . }}-kong-ingress-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "kong-base.name" . }}-kong-serviceaccount
  namespace: {{ .Release.Namespace }}
