apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-base.name" . }}-kong-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong
