apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-base.name" . }}-kong-ingress-controller
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: ingress-kong
