apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-base.name" . }}-kong-metrics
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9542
    protocol: TCP
  selector:
    app: kong
