apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-base.name" . }}-postgres
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
