apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kong-base.name" . }}-postgres
  namespace: {{.Release.Namespace}}
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: {{include "postgres.name" .}}
        image: postgres:9.5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{include "postgres.name" .}}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{include "postgres.name" .}}
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{include "postgres.name" .}}
              key: database
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
