apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  username: {{.Values.postgres.user | b64enc}}
  password: {{.Values.postgres.password | b64enc}}
  database: {{print "kong" | b64enc}}
