apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong-base.name" . }}-postgres
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  username: {{.Values.postgres.user | b64enc}}
  password: {{.Values.postgres.password | b64enc}}
  database: {{print "kong" | b64enc}}
